import React, { useRef, useContext, useState, useCallback} from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Companies from './companies'
import Footer from '../components/Footer'
import About from '../components/About'
import MissionStatement from '../components/MissionStatement'


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>ÆR Global</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
      
      <About />

      <MissionStatement />
    
    </div>
  )
}

export default Home
